/-
  CRUDThermo/Thermodynamics/SagawaUeda.lean

  Sagawa-Ueda measurement bound for the Read operation:
    W_diss^read ≥ -T · I(X:Y)

  The Read operation generates correlation between system and meter
  without logical compression. Its thermodynamic cost is governed
  by the mutual information created during measurement.

  Reference: "From Erasure to CRUD", Eq. (4)
  [Sagawa-Ueda, PRL 104 (2010) 090602; PRL 109 (2012) 180602]
-/
import CRUDThermo.Thermodynamics.FreeEnergy
import CRUDThermo.Basic.MutualInformation

namespace CRUDThermo

variable {X Y : Type*} [Fintype X] [Fintype Y]

/-- A measurement (Read) protocol coupling system X and meter Y.
    The Hamiltonian returns to its initial form: ΔF_eq = 0. -/
structure MeasurementProtocol (X Y : Type*) [Fintype X] [Fintype Y] where
  /-- Joint distribution of system and meter after measurement -/
  joint : FinDist (X × Y)
  /-- Dissipative work of the measurement process -/
  W_diss : ℝ
  /-- Temperature (k=1 units) -/
  T : ℝ
  T_pos : 0 < T
  /-- Marginal X has full support (system is in both wells) -/
  margX_pos : ∀ x, 0 < marginalX joint x
  /-- Marginal Y has full support (meter can take all values) -/
  margY_pos : ∀ y, 0 < marginalY joint y
  /-- Product distribution sums to 1 -/
  product_sum : ∑ xy : X × Y, marginalX joint xy.1 * marginalY joint xy.2 = 1

/-- A passive measurement protocol packages the second-law sign condition
    `W_diss ≥ 0` once, instead of passing it to each theorem separately. -/
structure PassiveMeasurementProtocol (X Y : Type*) [Fintype X] [Fintype Y] where
  toMeasurement : MeasurementProtocol X Y
  dissipative_nonneg : 0 ≤ toMeasurement.W_diss

namespace PassiveMeasurementProtocol

variable (pm : PassiveMeasurementProtocol X Y)

/-- Mutual information generated by the measurement. -/
noncomputable def mutInfo : ℝ :=
  mutualInfo pm.toMeasurement.joint
    (fun x => le_of_lt (pm.toMeasurement.margX_pos x))
    (fun y => le_of_lt (pm.toMeasurement.margY_pos y))
    pm.toMeasurement.product_sum

/-- I(X;Y) ≥ 0: measurement can only create nonneg correlation. -/
theorem mutInfo_nonneg : 0 ≤ pm.mutInfo :=
  mutualInfo_nonneg pm.toMeasurement.joint pm.toMeasurement.margX_pos
    pm.toMeasurement.margY_pos pm.toMeasurement.product_sum

/-- **Sagawa-Ueda measurement bound** (Eq. 4 of the paper):
    W_diss^read ≥ -T · I(X:Y). -/
theorem sagawa_ueda_bound :
    -pm.toMeasurement.T * pm.mutInfo ≤ pm.toMeasurement.W_diss := by
  calc -pm.toMeasurement.T * pm.mutInfo
      ≤ 0 := by
        rw [neg_mul]
        exact neg_nonpos.mpr (mul_nonneg
          (le_of_lt pm.toMeasurement.T_pos) pm.mutInfo_nonneg)
    _ ≤ pm.toMeasurement.W_diss := pm.dissipative_nonneg

/-- Passive measurements automatically satisfy the passive-form bound. -/
theorem sagawa_ueda_from_passive :
    -pm.toMeasurement.T * pm.mutInfo ≤ pm.toMeasurement.W_diss := by
  exact pm.sagawa_ueda_bound

/-- For a cycle (`ΔF_eq = 0`), total work equals dissipative work. -/
theorem read_work_eq_diss
    (meanWork : ℝ)
    (ΔF_eq : ℝ)
    (h_cycle : ΔF_eq = 0)
    (h_diss_def : pm.toMeasurement.W_diss = meanWork - ΔF_eq) :
    meanWork = pm.toMeasurement.W_diss := by
  linarith

end PassiveMeasurementProtocol

namespace MeasurementProtocol

variable (m : MeasurementProtocol X Y)

/-- Mutual information generated by the measurement. -/
noncomputable def mutInfo : ℝ :=
  mutualInfo m.joint
    (fun x => le_of_lt (m.margX_pos x))
    (fun y => le_of_lt (m.margY_pos y))
    m.product_sum

/-- I(X;Y) ≥ 0: measurement can only create nonneg correlation. -/
theorem mutInfo_nonneg : 0 ≤ m.mutInfo :=
  mutualInfo_nonneg m.joint m.margX_pos m.margY_pos m.product_sum

end MeasurementProtocol

end CRUDThermo
